### ISSUE TITLE
Normative statements checklist: 4. Data Model

### ISSUE THREAD

**Issue by rhiaro** [w3c/did-test-suite#73]
## 4.1 Extensibility

* [ ] For maximum interoperability, it is RECOMMENDED that extensions use the W3C DID Specification Registries mechanism [DID-SPEC-REGISTRIES].
* [ ] Representations MAY define other extensibility mechanisms, including ones that do not require the use of the DID Specification Registries. Such extension mechanisms SHOULD support lossless conversion into any other conformant representation.
* [ ] Extension mechanisms for a representation SHOULD define a mapping of all properties and representation syntax into the data model and its type system.

**Comment by msporny** [comment]
I have reviewed all of these normative statements. There are no MUST statements and thus no requirement that these are implemented in the test suite. In addition, all of these statements are only human testable and thus shouldn't be in the test suite.
